concurrency: ${{ github.workflow }}/${{ github.ref }}

on:
  workflow_dispatch:
    inputs:
      push:
        description: "Push built image"
        default: true
        required: false
        type: boolean

  workflow_call:
    inputs:
      push:
        description: "Push built image"
        default: true
        required: false
        type: boolean

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: fedora-38
            dockerfile: fedora.dockerfile

          - image: fedora-39
            dockerfile: fedora.dockerfile

          - image: fedora-40
            dockerfile: fedora.dockerfile

          - image: centos-9
            dockerfile: fedora.dockerfile

          - image: debian-12
            dockerfile: debian.dockerfile

          - image: ubuntu-22.04
            dockerfile: debian.dockerfile

          - image: ubuntu-23.10
            dockerfile: debian.dockerfile

          - image: archlinux
            dockerfile: archlinux.dockerfile

          - image: opensuse-tumbleweed
            dockerfile: suse.dockerfile

          - image: opensuse-leap-15.5
            dockerfile: suse.dockerfile

    timeout-minutes: 15
    env:
      IMAGE: ghcr.io/${{ github.repository }}/${{ matrix.image }}
      # renovate: datasource=github-tags depName=containers/crun
      CRUN_VER: '1.14.4'
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}

      - id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          build-args: |
            base_image=${{ matrix.image }}
          pull: true
          push: ${{ inputs.push }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          annotations: ${{ steps.docker_meta.outputs.annotations }}
          cache-from: |
            ${{ steps.docker_meta.outputs.tags }}
            ${{ env.IMAGE }}:master
          cache-to: type=inline

      - run: |
          # https://noobient.com/2023/11/15/fixing-ubuntu-containers-failing-to-start-with-systemd/
          mkdir -p "${HOME}/.local/bin"
          curl -L "https://github.com/containers/crun/releases/download/${CRUN_VER}/crun-${CRUN_VER}-linux-amd64" -o "${HOME}/.local/bin/crun"
          chmod +x "${HOME}/.local/bin/crun"
          mkdir -p "${HOME}/.config/containers"
          cat << EOF > "${HOME}/.config/containers/containers.conf"
          [engine.runtimes]
          crun = [
            "${HOME}/.local/bin/crun",
            "/usr/bin/crun"
          ]
          EOF

      - run: podman pull docker-daemon:${{ steps.docker_build.outputs.imageid }} | tee .podman-image-id

      - run: DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends x11-utils

      - id: gnome-session-x11
        name: Test gnome-session-x11
        run: test/test.sh $(cat .podman-image-id) gnome-session-x11

      - id: gnome-session-wayland
        name: Test gnome-session-wayland
        run: test/test.sh $(cat .podman-image-id) gnome-session-wayland

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image }}-screenshots
          path: test/*.png
        if: ${{ always() && steps.gnome-session-x11.conclusion == 'success' || steps.gnome-session-wayland.conclusion == 'success' }}
