name: Container registry cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "15 1 * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    defaults:
      run:
        working-directory: .github/registry-cleanup

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: node .
        env:
          GITHUB_TOKEN: ${{ secrets.CLEAN_TOKEN }}
