on:
  workflow_call:
    inputs:
      dry-run:
        description: "Don't delete images, only print names and URLs"
        required: true
        type: boolean

    secrets:
      packages-api-token:
        description: "A personal access token with packages:delete permission"
        required: true

jobs:
  cleanup:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .github/registry-cleanup

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: ./cleanup.js ${{ inputs.dry-run && '-n' || '' }} -t "${{ secrets.packages-api-token }}"
