name: master

on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/registry-cleanup/**
      - .github/workflows/ghcr-*.yml
      - renovate.json
      - README.md
      - LICENSE

permissions:
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/common.yml
  tag:
    needs: ci
    uses: ./.github/workflows/tag.yml
    permissions:
      contents: write
      actions: write
