name: push

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
    tags:
      - "*"
    paths-ignore:
      - .github/registry-cleanup/**
      - .github/workflows/ghcr-*.yml

permissions:
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/common.yml
